// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Global$ReactHooksTemplate = require("./Global.bs.js");
var Sidebar1$ReactHooksTemplate = require("./Sidebar1.bs.js");
var PlayingCardRotatable$ReactHooksTemplate = require("./PlayingCardRotatable.bs.js");

function s2e(prim) {
  return prim;
}

function App(Props) {
  var match = React.useReducer(Global$ReactHooksTemplate.reducer, /* record */[/* cardsDealerPlus0 : [] */0]);
  return React.createElement("div", {
              id: "main"
            }, React.createElement("div", undefined, $$Array.of_list(List.map((function (param) {
                            var index = param[0];
                            return React.createElement(PlayingCardRotatable$ReactHooksTemplate.make, {
                                        cardIndex: index,
                                        filePath: "./images/" + (param[1] + ".svg"),
                                        leftVw: 50.0,
                                        topVh: 75.0,
                                        parentElementWidthPx: ( window.innerWidth ),
                                        parentElementHeightPx: ( window.innerHeight ),
                                        key: String(index)
                                      });
                          }), match[0][/* cardsDealerPlus0 */0]))), React.createElement("div", {
                  style: {
                    left: "50%",
                    position: "absolute",
                    top: "15%"
                  }
                }, "N"), React.createElement("div", {
                  style: {
                    left: "50%",
                    position: "absolute",
                    top: "85%"
                  }
                }, "S"), React.createElement("div", {
                  style: {
                    left: "15%",
                    position: "absolute",
                    top: "50%"
                  }
                }, "W"), React.createElement("div", {
                  style: {
                    left: "85%",
                    position: "absolute",
                    top: "50%"
                  }
                }, "E"), React.createElement("div", {
                  id: "sidebar1"
                }, React.createElement(Sidebar1$ReactHooksTemplate.make, {
                      dispatch: match[1]
                    })), React.createElement("div", {
                  id: "sidebar2"
                }, "Sidebar2"), React.createElement("div", {
                  id: "sidebar3"
                }, "Sidebar3"));
}

var make = App;

exports.s2e = s2e;
exports.make = make;
/* react Not a pure module */
