// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Global$ReactHooksTemplate = require("./Global.bs.js");
var Sidebar1$ReactHooksTemplate = require("./Sidebar1.bs.js");
var FlipButton$ReactHooksTemplate = require("./FlipButton.bs.js");
var PlayingCardRotatable$ReactHooksTemplate = require("./PlayingCardRotatable.bs.js");

function App(Props) {
  var match = React.useReducer(Global$ReactHooksTemplate.reducer, Global$ReactHooksTemplate.initialState);
  var dispatch = match[1];
  return React.createElement("div", {
              id: "main"
            }, React.createElement("div", undefined, React.createElement(PlayingCardRotatable$ReactHooksTemplate.make, {
                      cardIndex: 0,
                      filePath: "./images/1B.svg",
                      leftVw: 50.0,
                      topVh: 75.0,
                      parentElementWidthPx: window.innerWidth,
                      parentElementHeightPx: window.innerHeight,
                      key: String(0)
                    })), React.createElement("div", undefined, React.createElement(PlayingCardRotatable$ReactHooksTemplate.make, {
                      cardIndex: 0,
                      filePath: "./images/1B.svg",
                      leftVw: 25.0,
                      topVh: 50.0,
                      parentElementWidthPx: window.innerWidth,
                      parentElementHeightPx: window.innerHeight,
                      key: String(0)
                    })), React.createElement("div", undefined, React.createElement(PlayingCardRotatable$ReactHooksTemplate.make, {
                      cardIndex: 0,
                      filePath: "./images/1B.svg",
                      leftVw: 50.0,
                      topVh: 25.0,
                      parentElementWidthPx: window.innerWidth,
                      parentElementHeightPx: window.innerHeight,
                      key: String(0)
                    })), React.createElement("div", undefined, React.createElement(PlayingCardRotatable$ReactHooksTemplate.make, {
                      cardIndex: 0,
                      filePath: "./images/1B.svg",
                      leftVw: 75.0,
                      topVh: 50.0,
                      parentElementWidthPx: window.innerWidth,
                      parentElementHeightPx: window.innerHeight,
                      key: String(0)
                    })), React.createElement("div", {
                  style: {
                    left: "50%",
                    position: "absolute",
                    top: "40%"
                  }
                }, React.createElement(FlipButton$ReactHooksTemplate.make, {
                      dispatch: dispatch,
                      location: "North"
                    })), React.createElement("div", {
                  style: {
                    left: "50%",
                    position: "absolute",
                    top: "90%"
                  }
                }, React.createElement(FlipButton$ReactHooksTemplate.make, {
                      dispatch: dispatch,
                      location: "South"
                    })), React.createElement("div", {
                  style: {
                    left: "25%",
                    position: "absolute",
                    top: "65%"
                  }
                }, React.createElement(FlipButton$ReactHooksTemplate.make, {
                      dispatch: dispatch,
                      location: "West"
                    })), React.createElement("div", {
                  style: {
                    left: "75%",
                    position: "absolute",
                    top: "65%"
                  }
                }, React.createElement(FlipButton$ReactHooksTemplate.make, {
                      dispatch: dispatch,
                      location: "East"
                    })), React.createElement("div", {
                  id: "sidebar1"
                }, React.createElement(Sidebar1$ReactHooksTemplate.make, {
                      dispatch: dispatch
                    })), React.createElement("div", {
                  id: "sidebar2"
                }, Global$ReactHooksTemplate.s2e("Sidebar2")), React.createElement("div", {
                  id: "sidebar3"
                }, Global$ReactHooksTemplate.s2e("Sidebar3")));
}

var make = App;

exports.make = make;
/* react Not a pure module */
