// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Ute$ReactHooksTemplate = require("./Ute.bs.js");

function reducer(state, action) {
  if (action) {
    Ute$ReactHooksTemplate.deal(/* () */0);
    var result = $$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.setOfCardsDealerPlus1);
    console.log(result);
    return state;
  } else {
    return /* record */[/* cardsDealerPlus0 : :: */[
              /* tuple */[
                -8,
                "2S"
              ],
              /* :: */[
                /* tuple */[
                  -7,
                  "TC"
                ],
                /* :: */[
                  /* tuple */[
                    -6,
                    "AC"
                  ],
                  /* :: */[
                    /* tuple */[
                      -5,
                      "3C"
                    ],
                    /* :: */[
                      /* tuple */[
                        -4,
                        "KD"
                      ],
                      /* :: */[
                        /* tuple */[
                          -3,
                          "2S"
                        ],
                        /* :: */[
                          /* tuple */[
                            -2,
                            "4H"
                          ],
                          /* :: */[
                            /* tuple */[
                              -1,
                              "TS"
                            ],
                            /* :: */[
                              /* tuple */[
                                0,
                                "2D"
                              ],
                              /* :: */[
                                /* tuple */[
                                  1,
                                  "3S"
                                ],
                                /* :: */[
                                  /* tuple */[
                                    2,
                                    "5C"
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      3,
                                      "QH"
                                    ],
                                    /* :: */[
                                      /* tuple */[
                                        4,
                                        "9S"
                                      ],
                                      state[/* cardsDealerPlus0 */0]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]];
  }
}

exports.reducer = reducer;
/* Ute-ReactHooksTemplate Not a pure module */
