// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReactHooksTemplate = require("./App.bs.js");

 window.onresize = forceGlobalReRender 
;

function forceGlobalReRender(param) {
  console.log("ReRender whole window");
  return ReactDOMRe.renderToElementWithId(React.createElement(App$ReactHooksTemplate.make, { }), "root");
}

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactHooksTemplate.make, { }), "root");

exports.forceGlobalReRender = forceGlobalReRender;
/*  Not a pure module */
