// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Ute$ReactHooksTemplate = require("./Ute.bs.js");

function impureShuffleOfPack(param) {
  Ute$ReactHooksTemplate.impureGetRandomSeedUpTo60k(undefined);
  console.log($$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.arrayOfCards));
  Ute$ReactHooksTemplate.allocateShuffledToLocation(/* West */3);
  $$Array.sort((function (param, param$1) {
          return Ute$ReactHooksTemplate.compareCardValue(/* NO_TRUMPS */0, param, param$1);
        }), Ute$ReactHooksTemplate.cardsNorth);
  $$Array.sort((function (param, param$1) {
          return Ute$ReactHooksTemplate.compareCardValue(/* NO_TRUMPS */0, param, param$1);
        }), Ute$ReactHooksTemplate.cardsEast);
  $$Array.sort((function (param, param$1) {
          return Ute$ReactHooksTemplate.compareCardValue(/* NO_TRUMPS */0, param, param$1);
        }), Ute$ReactHooksTemplate.cardsSouth);
  $$Array.sort((function (param, param$1) {
          return Ute$ReactHooksTemplate.compareCardValue(/* NO_TRUMPS */0, param, param$1);
        }), Ute$ReactHooksTemplate.cardsWest);
  var cardsNorthAsString = $$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.cardsNorth);
  var cardsEastAsString = $$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.cardsEast);
  var cardsSouthAsString = $$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.cardsSouth);
  var cardsWestAsString = $$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.cardsWest);
  var cardsNorthWithIndex = $$Array.mapi((function (k, v) {
          return /* tuple */[
                  k,
                  v
                ];
        }), cardsNorthAsString);
  var cardsEastWithIndex = $$Array.mapi((function (k, v) {
          return /* tuple */[
                  k,
                  v
                ];
        }), cardsEastAsString);
  var cardsSouthWithIndex = $$Array.mapi((function (k, v) {
          return /* tuple */[
                  k,
                  v
                ];
        }), cardsSouthAsString);
  var cardsWestWithIndex = $$Array.mapi((function (k, v) {
          return /* tuple */[
                  k,
                  v
                ];
        }), cardsWestAsString);
  return {
          cardsNorth: cardsNorthWithIndex,
          cardsEast: cardsEastWithIndex,
          cardsSouth: cardsSouthWithIndex,
          cardsWest: cardsWestWithIndex,
          northIsFlipped: false,
          eastIsFlipped: false,
          southIsFlipped: false,
          westIsFlipped: false,
          dealer: undefined,
          shuffleCount: 0
        };
}

exports.impureShuffleOfPack = impureShuffleOfPack;
/* Ute-ReactHooksTemplate Not a pure module */
