// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Ute$ReactHooksTemplate = require("./Ute.bs.js");

function impureShuffleOfPack(param) {
  var seed = Ute$ReactHooksTemplate.impureGetRandomSeedUpTo60k(undefined);
  Ute$ReactHooksTemplate.shuffleArrayInPlace(Ute$ReactHooksTemplate.arrayOfCards, seed);
  Ute$ReactHooksTemplate.deal(undefined);
  $$Array.sort((function (param, param$1) {
          return Ute$ReactHooksTemplate.compareCardValue(/* NO_TRUMPS */0, param, param$1);
        }), Ute$ReactHooksTemplate.setOfCardsDealerPlus1);
  $$Array.sort((function (param, param$1) {
          return Ute$ReactHooksTemplate.compareCardValue(/* NO_TRUMPS */0, param, param$1);
        }), Ute$ReactHooksTemplate.setOfCardsDealerPlus2);
  $$Array.sort((function (param, param$1) {
          return Ute$ReactHooksTemplate.compareCardValue(/* NO_TRUMPS */0, param, param$1);
        }), Ute$ReactHooksTemplate.setOfCardsDealerPlus3);
  $$Array.sort((function (param, param$1) {
          return Ute$ReactHooksTemplate.compareCardValue(/* NO_TRUMPS */0, param, param$1);
        }), Ute$ReactHooksTemplate.setOfCardsDealerPlus0);
  var setOfCardsAsStringDealerPlus1 = $$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.setOfCardsDealerPlus1);
  var setOfCardsAsStringDealerPlus2 = $$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.setOfCardsDealerPlus2);
  var setOfCardsAsStringDealerPlus3 = $$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.setOfCardsDealerPlus3);
  var setOfCardsAsStringDealerPlus0 = $$Array.map(Ute$ReactHooksTemplate.cardToString, Ute$ReactHooksTemplate.setOfCardsDealerPlus0);
  var setOfCardsWithIndexDealerPlus1 = $$Array.mapi((function (k, v) {
          return /* tuple */[
                  k,
                  v
                ];
        }), setOfCardsAsStringDealerPlus1);
  var setOfCardsWithIndexDealerPlus2 = $$Array.mapi((function (k, v) {
          return /* tuple */[
                  k,
                  v
                ];
        }), setOfCardsAsStringDealerPlus2);
  var setOfCardsWithIndexDealerPlus3 = $$Array.mapi((function (k, v) {
          return /* tuple */[
                  k,
                  v
                ];
        }), setOfCardsAsStringDealerPlus3);
  var setOfCardsWithIndexDealerPlus0 = $$Array.mapi((function (k, v) {
          return /* tuple */[
                  k,
                  v
                ];
        }), setOfCardsAsStringDealerPlus0);
  return {
          dealerPlus1: setOfCardsWithIndexDealerPlus1,
          dealerPlus2: setOfCardsWithIndexDealerPlus2,
          dealerPlus3: setOfCardsWithIndexDealerPlus3,
          dealerPlus0: setOfCardsWithIndexDealerPlus0,
          plus1IsFlipped: true,
          plus2IsFlipped: true,
          plus3IsFlipped: true,
          plus0IsFlipped: true
        };
}

exports.impureShuffleOfPack = impureShuffleOfPack;
/* Ute-ReactHooksTemplate Not a pure module */
