// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Random = require("bs-platform/lib/js/random.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var orderedListOfCards = /* :: */[
  /* tuple */[
    /* Ace */0,
    /* Spades */0,
    /* Hand */1
  ],
  /* :: */[
    /* tuple */[
      /* King */1,
      /* Spades */0,
      /* Hand */1
    ],
    /* :: */[
      /* tuple */[
        /* Queen */2,
        /* Spades */0,
        /* Hand */1
      ],
      /* :: */[
        /* tuple */[
          /* Jack */3,
          /* Spades */0,
          /* Hand */1
        ],
        /* :: */[
          /* tuple */[
            /* Ten */4,
            /* Spades */0,
            /* Hand */1
          ],
          /* :: */[
            /* tuple */[
              /* Nine */5,
              /* Spades */0,
              /* Hand */1
            ],
            /* :: */[
              /* tuple */[
                /* Eight */6,
                /* Spades */0,
                /* Hand */1
              ],
              /* :: */[
                /* tuple */[
                  /* Seven */7,
                  /* Spades */0,
                  /* Hand */1
                ],
                /* :: */[
                  /* tuple */[
                    /* Six */8,
                    /* Spades */0,
                    /* Dealer */0
                  ],
                  /* :: */[
                    /* tuple */[
                      /* Five */9,
                      /* Spades */0,
                      /* Dealer */0
                    ],
                    /* :: */[
                      /* tuple */[
                        /* Four */10,
                        /* Spades */0,
                        /* Dealer */0
                      ],
                      /* :: */[
                        /* tuple */[
                          /* Three */11,
                          /* Spades */0,
                          /* Dealer */0
                        ],
                        /* :: */[
                          /* tuple */[
                            /* Two */12,
                            /* Spades */0,
                            /* Dealer */0
                          ],
                          /* :: */[
                            /* tuple */[
                              /* Ace */0,
                              /* Hearts */1,
                              /* Dealer */0
                            ],
                            /* :: */[
                              /* tuple */[
                                /* King */1,
                                /* Hearts */1,
                                /* Dealer */0
                              ],
                              /* :: */[
                                /* tuple */[
                                  /* Queen */2,
                                  /* Hearts */1,
                                  /* Dealer */0
                                ],
                                /* :: */[
                                  /* tuple */[
                                    /* Jack */3,
                                    /* Hearts */1,
                                    /* Dealer */0
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      /* Ten */4,
                                      /* Hearts */1,
                                      /* Dealer */0
                                    ],
                                    /* :: */[
                                      /* tuple */[
                                        /* Nine */5,
                                        /* Hearts */1,
                                        /* Dealer */0
                                      ],
                                      /* :: */[
                                        /* tuple */[
                                          /* Eight */6,
                                          /* Hearts */1,
                                          /* Dealer */0
                                        ],
                                        /* :: */[
                                          /* tuple */[
                                            /* Seven */7,
                                            /* Hearts */1,
                                            /* Dealer */0
                                          ],
                                          /* :: */[
                                            /* tuple */[
                                              /* Six */8,
                                              /* Hearts */1,
                                              /* Dealer */0
                                            ],
                                            /* :: */[
                                              /* tuple */[
                                                /* Five */9,
                                                /* Hearts */1,
                                                /* Dealer */0
                                              ],
                                              /* :: */[
                                                /* tuple */[
                                                  /* Four */10,
                                                  /* Hearts */1,
                                                  /* Dealer */0
                                                ],
                                                /* :: */[
                                                  /* tuple */[
                                                    /* Three */11,
                                                    /* Hearts */1,
                                                    /* Dealer */0
                                                  ],
                                                  /* :: */[
                                                    /* tuple */[
                                                      /* Two */12,
                                                      /* Hearts */1,
                                                      /* Dealer */0
                                                    ],
                                                    /* :: */[
                                                      /* tuple */[
                                                        /* Ace */0,
                                                        /* Clubs */3,
                                                        /* Dealer */0
                                                      ],
                                                      /* :: */[
                                                        /* tuple */[
                                                          /* King */1,
                                                          /* Clubs */3,
                                                          /* Dealer */0
                                                        ],
                                                        /* :: */[
                                                          /* tuple */[
                                                            /* Queen */2,
                                                            /* Clubs */3,
                                                            /* Dealer */0
                                                          ],
                                                          /* :: */[
                                                            /* tuple */[
                                                              /* Jack */3,
                                                              /* Clubs */3,
                                                              /* Dealer */0
                                                            ],
                                                            /* :: */[
                                                              /* tuple */[
                                                                /* Ten */4,
                                                                /* Clubs */3,
                                                                /* Dealer */0
                                                              ],
                                                              /* :: */[
                                                                /* tuple */[
                                                                  /* Nine */5,
                                                                  /* Clubs */3,
                                                                  /* Dealer */0
                                                                ],
                                                                /* :: */[
                                                                  /* tuple */[
                                                                    /* Eight */6,
                                                                    /* Clubs */3,
                                                                    /* Dealer */0
                                                                  ],
                                                                  /* :: */[
                                                                    /* tuple */[
                                                                      /* Seven */7,
                                                                      /* Clubs */3,
                                                                      /* Dealer */0
                                                                    ],
                                                                    /* :: */[
                                                                      /* tuple */[
                                                                        /* Six */8,
                                                                        /* Clubs */3,
                                                                        /* Dealer */0
                                                                      ],
                                                                      /* :: */[
                                                                        /* tuple */[
                                                                          /* Five */9,
                                                                          /* Clubs */3,
                                                                          /* Dealer */0
                                                                        ],
                                                                        /* :: */[
                                                                          /* tuple */[
                                                                            /* Four */10,
                                                                            /* Clubs */3,
                                                                            /* Dealer */0
                                                                          ],
                                                                          /* :: */[
                                                                            /* tuple */[
                                                                              /* Three */11,
                                                                              /* Clubs */3,
                                                                              /* Dealer */0
                                                                            ],
                                                                            /* :: */[
                                                                              /* tuple */[
                                                                                /* Two */12,
                                                                                /* Clubs */3,
                                                                                /* Dealer */0
                                                                              ],
                                                                              /* :: */[
                                                                                /* tuple */[
                                                                                  /* Ace */0,
                                                                                  /* Diamonds */2,
                                                                                  /* Dealer */0
                                                                                ],
                                                                                /* :: */[
                                                                                  /* tuple */[
                                                                                    /* King */1,
                                                                                    /* Diamonds */2,
                                                                                    /* Dealer */0
                                                                                  ],
                                                                                  /* :: */[
                                                                                    /* tuple */[
                                                                                      /* Queen */2,
                                                                                      /* Diamonds */2,
                                                                                      /* Dealer */0
                                                                                    ],
                                                                                    /* :: */[
                                                                                      /* tuple */[
                                                                                        /* Jack */3,
                                                                                        /* Diamonds */2,
                                                                                        /* Dealer */0
                                                                                      ],
                                                                                      /* :: */[
                                                                                        /* tuple */[
                                                                                          /* Ten */4,
                                                                                          /* Diamonds */2,
                                                                                          /* Dealer */0
                                                                                        ],
                                                                                        /* :: */[
                                                                                          /* tuple */[
                                                                                            /* Nine */5,
                                                                                            /* Diamonds */2,
                                                                                            /* Dealer */0
                                                                                          ],
                                                                                          /* :: */[
                                                                                            /* tuple */[
                                                                                              /* Eight */6,
                                                                                              /* Diamonds */2,
                                                                                              /* Dealer */0
                                                                                            ],
                                                                                            /* :: */[
                                                                                              /* tuple */[
                                                                                                /* Seven */7,
                                                                                                /* Diamonds */2,
                                                                                                /* Dealer */0
                                                                                              ],
                                                                                              /* :: */[
                                                                                                /* tuple */[
                                                                                                  /* Six */8,
                                                                                                  /* Diamonds */2,
                                                                                                  /* Dealer */0
                                                                                                ],
                                                                                                /* :: */[
                                                                                                  /* tuple */[
                                                                                                    /* Five */9,
                                                                                                    /* Diamonds */2,
                                                                                                    /* Dealer */0
                                                                                                  ],
                                                                                                  /* :: */[
                                                                                                    /* tuple */[
                                                                                                      /* Four */10,
                                                                                                      /* Diamonds */2,
                                                                                                      /* Dealer */0
                                                                                                    ],
                                                                                                    /* :: */[
                                                                                                      /* tuple */[
                                                                                                        /* Three */11,
                                                                                                        /* Diamonds */2,
                                                                                                        /* Dealer */0
                                                                                                      ],
                                                                                                      /* :: */[
                                                                                                        /* tuple */[
                                                                                                          /* Two */12,
                                                                                                          /* Diamonds */2,
                                                                                                          /* Dealer */0
                                                                                                        ],
                                                                                                        /* [] */0
                                                                                                      ]
                                                                                                    ]
                                                                                                  ]
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var arrayOfCards = $$Array.of_list(orderedListOfCards);

function suitToString(playingCardSuit) {
  switch (playingCardSuit) {
    case /* Spades */0 :
        return "S";
    case /* Hearts */1 :
        return "H";
    case /* Diamonds */2 :
        return "D";
    case /* Clubs */3 :
        return "C";
    case /* NoSuit */4 :
        return "!";
    
  }
}

function rankToString(playingCardRank) {
  switch (playingCardRank) {
    case /* Ace */0 :
        return "A";
    case /* King */1 :
        return "K";
    case /* Queen */2 :
        return "Q";
    case /* Jack */3 :
        return "J";
    case /* Ten */4 :
        return "T";
    case /* Nine */5 :
        return "9";
    case /* Eight */6 :
        return "8";
    case /* Seven */7 :
        return "7";
    case /* Six */8 :
        return "6";
    case /* Five */9 :
        return "5";
    case /* Four */10 :
        return "4";
    case /* Three */11 :
        return "3";
    case /* Two */12 :
        return "2";
    case /* NoRank */13 :
        return "!";
    
  }
}

function cardToString(playingCard) {
  return /* tuple */[
          rankToString(playingCard[0]) + suitToString(playingCard[1]),
          playingCard[2]
        ];
}

function cardToValue(gameDenomination, playingCard) {
  var suitToValue = function (playingCardSuit, gameDenomination) {
    switch (playingCardSuit) {
      case /* Spades */0 :
          return 42;
      case /* Hearts */1 :
          if (gameDenomination && gameDenomination[0] === 1) {
            return 56;
          } else {
            return 28;
          }
      case /* Diamonds */2 :
          if (gameDenomination && gameDenomination[0] === 2) {
            return 56;
          } else {
            return 0;
          }
      case /* Clubs */3 :
          if (gameDenomination && gameDenomination[0] === 3) {
            return 56;
          } else {
            return 14;
          }
      case /* NoSuit */4 :
          return -14;
      
    }
  };
  var rankToValue = function (playingCardRank) {
    switch (playingCardRank) {
      case /* Ace */0 :
          return 14;
      case /* King */1 :
          return 13;
      case /* Queen */2 :
          return 12;
      case /* Jack */3 :
          return 11;
      case /* Ten */4 :
          return 10;
      case /* Nine */5 :
          return 9;
      case /* Eight */6 :
          return 8;
      case /* Seven */7 :
          return 7;
      case /* Six */8 :
          return 6;
      case /* Five */9 :
          return 5;
      case /* Four */10 :
          return 4;
      case /* Three */11 :
          return 3;
      case /* Two */12 :
          return 2;
      case /* NoRank */13 :
          return 0;
      
    }
  };
  return rankToValue(playingCard[0]) + suitToValue(playingCard[1], gameDenomination) | 0;
}

function compareCardValue(denom, cardA, cardB) {
  if (cardToValue(denom, cardA) > cardToValue(denom, cardB)) {
    return -1;
  } else {
    return 1;
  }
}

function shuffleArrayInPlace(arr, seed) {
  Random.init(seed);
  for(var n = arr.length - 1 | 0; n >= 1; --n){
    var k = Random.$$int(n + 1 | 0);
    var temp = Caml_array.caml_array_get(arr, n);
    Caml_array.caml_array_set(arr, n, Caml_array.caml_array_get(arr, k));
    Caml_array.caml_array_set(arr, k, temp);
  }
  
}

var cardsNorth = Caml_array.caml_make_vect(13, /* tuple */[
      /* NoRank */13,
      /* NoSuit */4,
      /* Dealer */0
    ]);

var cardsEast = Caml_array.caml_make_vect(13, /* tuple */[
      /* NoRank */13,
      /* NoSuit */4,
      /* Dealer */0
    ]);

var cardsSouth = Caml_array.caml_make_vect(13, /* tuple */[
      /* NoRank */13,
      /* NoSuit */4,
      /* Dealer */0
    ]);

var cardsWest = Caml_array.caml_make_vect(13, /* tuple */[
      /* NoRank */13,
      /* NoSuit */4,
      /* Dealer */0
    ]);

function shuffleByModulo(k) {
  for(var i = 0; i <= 51; ++i){
    if (i % 4 === k) {
      Caml_array.caml_array_set(cardsNorth, i / 4 | 0, Caml_array.caml_array_get(arrayOfCards, i));
    } else if (i % 4 === (k + 1 | 0)) {
      Caml_array.caml_array_set(cardsEast, i / 4 | 0, Caml_array.caml_array_get(arrayOfCards, i));
    } else if (i % 4 === (k + 2 | 0)) {
      Caml_array.caml_array_set(cardsSouth, i / 4 | 0, Caml_array.caml_array_get(arrayOfCards, i));
    } else if (i % 4 === (k + 3 | 0)) {
      Caml_array.caml_array_set(cardsWest, i / 4 | 0, Caml_array.caml_array_get(arrayOfCards, i));
    } else {
      console.log("should be unreachable, i=" + String(i));
    }
  }
  
}

function allocateShuffledToLocation(loc) {
  switch (loc) {
    case /* North */0 :
        return shuffleByModulo(3);
    case /* East */1 :
        return shuffleByModulo(2);
    case /* South */2 :
        return shuffleByModulo(1);
    case /* West */3 :
        return shuffleByModulo(0);
    
  }
}

function impureGetRandomSeedUpTo60k(param) {
  var now = new Date();
  return now.getSeconds() * 1000.0 + now.getMilliseconds() | 0;
}

exports.orderedListOfCards = orderedListOfCards;
exports.arrayOfCards = arrayOfCards;
exports.suitToString = suitToString;
exports.rankToString = rankToString;
exports.cardToString = cardToString;
exports.cardToValue = cardToValue;
exports.compareCardValue = compareCardValue;
exports.shuffleArrayInPlace = shuffleArrayInPlace;
exports.cardsNorth = cardsNorth;
exports.cardsEast = cardsEast;
exports.cardsSouth = cardsSouth;
exports.cardsWest = cardsWest;
exports.shuffleByModulo = shuffleByModulo;
exports.allocateShuffledToLocation = allocateShuffledToLocation;
exports.impureGetRandomSeedUpTo60k = impureGetRandomSeedUpTo60k;
/* arrayOfCards Not a pure module */
