// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Random = require("bs-platform/lib/js/random.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var orderedListOfCards = /* :: */[
  /* tuple */[
    /* Ace */0,
    /* Spades */0
  ],
  /* :: */[
    /* tuple */[
      /* King */1,
      /* Spades */0
    ],
    /* :: */[
      /* tuple */[
        /* Queen */2,
        /* Spades */0
      ],
      /* :: */[
        /* tuple */[
          /* Jack */3,
          /* Spades */0
        ],
        /* :: */[
          /* tuple */[
            /* Ten */4,
            /* Spades */0
          ],
          /* :: */[
            /* tuple */[
              /* Nine */5,
              /* Spades */0
            ],
            /* :: */[
              /* tuple */[
                /* Eight */6,
                /* Spades */0
              ],
              /* :: */[
                /* tuple */[
                  /* Seven */7,
                  /* Spades */0
                ],
                /* :: */[
                  /* tuple */[
                    /* Six */8,
                    /* Spades */0
                  ],
                  /* :: */[
                    /* tuple */[
                      /* Five */9,
                      /* Spades */0
                    ],
                    /* :: */[
                      /* tuple */[
                        /* Four */10,
                        /* Spades */0
                      ],
                      /* :: */[
                        /* tuple */[
                          /* Three */11,
                          /* Spades */0
                        ],
                        /* :: */[
                          /* tuple */[
                            /* Two */12,
                            /* Spades */0
                          ],
                          /* :: */[
                            /* tuple */[
                              /* Ace */0,
                              /* Hearts */1
                            ],
                            /* :: */[
                              /* tuple */[
                                /* King */1,
                                /* Hearts */1
                              ],
                              /* :: */[
                                /* tuple */[
                                  /* Queen */2,
                                  /* Hearts */1
                                ],
                                /* :: */[
                                  /* tuple */[
                                    /* Jack */3,
                                    /* Hearts */1
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      /* Ten */4,
                                      /* Hearts */1
                                    ],
                                    /* :: */[
                                      /* tuple */[
                                        /* Nine */5,
                                        /* Hearts */1
                                      ],
                                      /* :: */[
                                        /* tuple */[
                                          /* Eight */6,
                                          /* Hearts */1
                                        ],
                                        /* :: */[
                                          /* tuple */[
                                            /* Seven */7,
                                            /* Hearts */1
                                          ],
                                          /* :: */[
                                            /* tuple */[
                                              /* Six */8,
                                              /* Hearts */1
                                            ],
                                            /* :: */[
                                              /* tuple */[
                                                /* Five */9,
                                                /* Hearts */1
                                              ],
                                              /* :: */[
                                                /* tuple */[
                                                  /* Four */10,
                                                  /* Hearts */1
                                                ],
                                                /* :: */[
                                                  /* tuple */[
                                                    /* Three */11,
                                                    /* Hearts */1
                                                  ],
                                                  /* :: */[
                                                    /* tuple */[
                                                      /* Two */12,
                                                      /* Hearts */1
                                                    ],
                                                    /* :: */[
                                                      /* tuple */[
                                                        /* Ace */0,
                                                        /* Diamonds */2
                                                      ],
                                                      /* :: */[
                                                        /* tuple */[
                                                          /* King */1,
                                                          /* Diamonds */2
                                                        ],
                                                        /* :: */[
                                                          /* tuple */[
                                                            /* Queen */2,
                                                            /* Diamonds */2
                                                          ],
                                                          /* :: */[
                                                            /* tuple */[
                                                              /* Jack */3,
                                                              /* Diamonds */2
                                                            ],
                                                            /* :: */[
                                                              /* tuple */[
                                                                /* Ten */4,
                                                                /* Diamonds */2
                                                              ],
                                                              /* :: */[
                                                                /* tuple */[
                                                                  /* Nine */5,
                                                                  /* Diamonds */2
                                                                ],
                                                                /* :: */[
                                                                  /* tuple */[
                                                                    /* Eight */6,
                                                                    /* Diamonds */2
                                                                  ],
                                                                  /* :: */[
                                                                    /* tuple */[
                                                                      /* Seven */7,
                                                                      /* Diamonds */2
                                                                    ],
                                                                    /* :: */[
                                                                      /* tuple */[
                                                                        /* Six */8,
                                                                        /* Diamonds */2
                                                                      ],
                                                                      /* :: */[
                                                                        /* tuple */[
                                                                          /* Five */9,
                                                                          /* Diamonds */2
                                                                        ],
                                                                        /* :: */[
                                                                          /* tuple */[
                                                                            /* Four */10,
                                                                            /* Diamonds */2
                                                                          ],
                                                                          /* :: */[
                                                                            /* tuple */[
                                                                              /* Three */11,
                                                                              /* Diamonds */2
                                                                            ],
                                                                            /* :: */[
                                                                              /* tuple */[
                                                                                /* Two */12,
                                                                                /* Diamonds */2
                                                                              ],
                                                                              /* :: */[
                                                                                /* tuple */[
                                                                                  /* Ace */0,
                                                                                  /* Clubs */3
                                                                                ],
                                                                                /* :: */[
                                                                                  /* tuple */[
                                                                                    /* King */1,
                                                                                    /* Clubs */3
                                                                                  ],
                                                                                  /* :: */[
                                                                                    /* tuple */[
                                                                                      /* Queen */2,
                                                                                      /* Clubs */3
                                                                                    ],
                                                                                    /* :: */[
                                                                                      /* tuple */[
                                                                                        /* Jack */3,
                                                                                        /* Clubs */3
                                                                                      ],
                                                                                      /* :: */[
                                                                                        /* tuple */[
                                                                                          /* Ten */4,
                                                                                          /* Clubs */3
                                                                                        ],
                                                                                        /* :: */[
                                                                                          /* tuple */[
                                                                                            /* Nine */5,
                                                                                            /* Clubs */3
                                                                                          ],
                                                                                          /* :: */[
                                                                                            /* tuple */[
                                                                                              /* Eight */6,
                                                                                              /* Clubs */3
                                                                                            ],
                                                                                            /* :: */[
                                                                                              /* tuple */[
                                                                                                /* Seven */7,
                                                                                                /* Clubs */3
                                                                                              ],
                                                                                              /* :: */[
                                                                                                /* tuple */[
                                                                                                  /* Six */8,
                                                                                                  /* Clubs */3
                                                                                                ],
                                                                                                /* :: */[
                                                                                                  /* tuple */[
                                                                                                    /* Five */9,
                                                                                                    /* Clubs */3
                                                                                                  ],
                                                                                                  /* :: */[
                                                                                                    /* tuple */[
                                                                                                      /* Four */10,
                                                                                                      /* Clubs */3
                                                                                                    ],
                                                                                                    /* :: */[
                                                                                                      /* tuple */[
                                                                                                        /* Three */11,
                                                                                                        /* Clubs */3
                                                                                                      ],
                                                                                                      /* :: */[
                                                                                                        /* tuple */[
                                                                                                          /* Two */12,
                                                                                                          /* Clubs */3
                                                                                                        ],
                                                                                                        /* [] */0
                                                                                                      ]
                                                                                                    ]
                                                                                                  ]
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var arrayOfCards = $$Array.of_list(orderedListOfCards);

function suitToString(playingCardSuit) {
  switch (playingCardSuit) {
    case /* Spades */0 :
        return "S";
    case /* Hearts */1 :
        return "H";
    case /* Diamonds */2 :
        return "D";
    case /* Clubs */3 :
        return "C";
    case /* NoSuit */4 :
        return "!";
    
  }
}

function suitToStringUnicode(playingCardSuit) {
  switch (playingCardSuit) {
    case /* Spades */0 :
        return "\u2660";
    case /* Hearts */1 :
        return "\u2665";
    case /* Diamonds */2 :
        return "\u2666";
    case /* Clubs */3 :
        return "\u2663";
    case /* NoSuit */4 :
        return "!";
    
  }
}

function rankToString(playingCardRank) {
  switch (playingCardRank) {
    case /* Ace */0 :
        return "A";
    case /* King */1 :
        return "K";
    case /* Queen */2 :
        return "Q";
    case /* Jack */3 :
        return "J";
    case /* Ten */4 :
        return "T";
    case /* Nine */5 :
        return "9";
    case /* Eight */6 :
        return "8";
    case /* Seven */7 :
        return "7";
    case /* Six */8 :
        return "6";
    case /* Five */9 :
        return "5";
    case /* Four */10 :
        return "4";
    case /* Three */11 :
        return "3";
    case /* Two */12 :
        return "2";
    case /* NoRank */13 :
        return "!";
    
  }
}

function cardToString(playingCard) {
  return rankToString(playingCard[0]) + suitToString(playingCard[1]);
}

function cardToValue(gameDenomination, playingCard) {
  var suitToValue = function (playingCardSuit, gameDenomination) {
    switch (playingCardSuit) {
      case /* Spades */0 :
          return 42;
      case /* Hearts */1 :
          if (gameDenomination && gameDenomination[0] === 1) {
            return 56;
          } else {
            return 28;
          }
      case /* Diamonds */2 :
          if (gameDenomination && gameDenomination[0] === 2) {
            return 56;
          } else {
            return 14;
          }
      case /* Clubs */3 :
          if (gameDenomination && gameDenomination[0] === 3) {
            return 56;
          } else {
            return 0;
          }
      case /* NoSuit */4 :
          return -14;
      
    }
  };
  var rankToValue = function (playingCardRank) {
    switch (playingCardRank) {
      case /* Ace */0 :
          return 14;
      case /* King */1 :
          return 13;
      case /* Queen */2 :
          return 12;
      case /* Jack */3 :
          return 11;
      case /* Ten */4 :
          return 10;
      case /* Nine */5 :
          return 9;
      case /* Eight */6 :
          return 8;
      case /* Seven */7 :
          return 7;
      case /* Six */8 :
          return 6;
      case /* Five */9 :
          return 5;
      case /* Four */10 :
          return 4;
      case /* Three */11 :
          return 3;
      case /* Two */12 :
          return 2;
      case /* NoRank */13 :
          return 0;
      
    }
  };
  return rankToValue(playingCard[0]) + suitToValue(playingCard[1], gameDenomination) | 0;
}

function compareCardValue(denom, cardA, cardB) {
  var match = cardToValue(denom, cardA) > cardToValue(denom, cardB);
  if (match) {
    return -1;
  } else {
    return 1;
  }
}

function shuffleArrayInPlace(arr, seed) {
  Random.init(seed);
  for(var n = arr.length - 1 | 0; n >= 1; --n){
    var k = Random.$$int(n + 1 | 0);
    var temp = Caml_array.caml_array_get(arr, n);
    Caml_array.caml_array_set(arr, n, Caml_array.caml_array_get(arr, k));
    Caml_array.caml_array_set(arr, k, temp);
  }
  return /* () */0;
}

var setOfCardsDealerPlus1 = Caml_array.caml_make_vect(13, /* tuple */[
      /* NoRank */13,
      /* NoSuit */4
    ]);

var setOfCardsDealerPlus2 = Caml_array.caml_make_vect(13, /* tuple */[
      /* NoRank */13,
      /* NoSuit */4
    ]);

var setOfCardsDealerPlus3 = Caml_array.caml_make_vect(13, /* tuple */[
      /* NoRank */13,
      /* NoSuit */4
    ]);

var setOfCardsDealerPlus0 = Caml_array.caml_make_vect(13, /* tuple */[
      /* NoRank */13,
      /* NoSuit */4
    ]);

function deal(param) {
  for(var i = 0; i <= 51; ++i){
    if (i % 4 === 0) {
      Caml_array.caml_array_set(setOfCardsDealerPlus1, i / 4 | 0, Caml_array.caml_array_get(arrayOfCards, i));
    } else if (i % 4 === 1) {
      Caml_array.caml_array_set(setOfCardsDealerPlus2, i / 4 | 0, Caml_array.caml_array_get(arrayOfCards, i));
    } else if (i % 4 === 2) {
      Caml_array.caml_array_set(setOfCardsDealerPlus3, i / 4 | 0, Caml_array.caml_array_get(arrayOfCards, i));
    } else if (i % 4 === 3) {
      Caml_array.caml_array_set(setOfCardsDealerPlus0, i / 4 | 0, Caml_array.caml_array_get(arrayOfCards, i));
    } else {
      console.log("should be unreachable");
    }
  }
  return /* () */0;
}

function displaySetOfCardsOnConsole(arr, suitAsString) {
  var l = $$Array.to_list(arr);
  if (l) {
    var hd = l[0];
    var remainder = displaySetOfCardsOnConsole($$Array.of_list(l[1]), suitToStringUnicode(hd[1]));
    var match = suitAsString === suitToStringUnicode(hd[1]);
    if (match) {
      return rankToString(hd[0]) + (" " + remainder);
    } else {
      return "  " + (suitToStringUnicode(hd[1]) + (" " + (rankToString(hd[0]) + (" " + remainder))));
    }
  } else {
    return "";
  }
}

function impureGetRandomSeedUpTo60k(param) {
  var now = new Date();
  return now.getSeconds() * 1000.0 + now.getMilliseconds() | 0;
}

exports.orderedListOfCards = orderedListOfCards;
exports.arrayOfCards = arrayOfCards;
exports.suitToString = suitToString;
exports.suitToStringUnicode = suitToStringUnicode;
exports.rankToString = rankToString;
exports.cardToString = cardToString;
exports.cardToValue = cardToValue;
exports.compareCardValue = compareCardValue;
exports.shuffleArrayInPlace = shuffleArrayInPlace;
exports.setOfCardsDealerPlus1 = setOfCardsDealerPlus1;
exports.setOfCardsDealerPlus2 = setOfCardsDealerPlus2;
exports.setOfCardsDealerPlus3 = setOfCardsDealerPlus3;
exports.setOfCardsDealerPlus0 = setOfCardsDealerPlus0;
exports.deal = deal;
exports.displaySetOfCardsOnConsole = displaySetOfCardsOnConsole;
exports.impureGetRandomSeedUpTo60k = impureGetRandomSeedUpTo60k;
/* arrayOfCards Not a pure module */
